---

- name: Install bash
  tags:
    - package
  package:
    name: bash

- name: Install system and user bashrc
  tags:
    - config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: bash.bashrc, dest: /etc/ }
    - { src: .bashrc, dest: /etc/.skel/ }
